name: 4222_Project
channels:
  - pytorch
  - nvidia
  - pyg
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - numpy=1.23
  - pandas=1.5
  - scipy=1.9
  - scikit-learn=1.2
  - matplotlib=3.6
  - seaborn=0.12
  - jupyter=1.0
  - networkx
  - requests=2.28
  - beautifulsoup4=4.11
  - lxml=4.9
  - tqdm=4.64
  - pyyaml=6.0
  - pip=23.0
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pyg=2.3.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.16
  - pytorch-cluster=1.6.1
  - pytorch-spline-conv=1.2.1
  - dgl=1.1.0
  - pip:
    - py2neo==2021.2.3
    - sentence-transformers==2.2.2
    - transformers==4.25.1
    - nltk==3.8.1
    - spacy==3.7.2
    - plotly==5.13.0
    - pyunpack==0.3.0
    - patool==1.12
    - python-dateutil==2.8.2
    - chardet==5.1.0
    - pillow==9.4.0
    - openpyxl==3.1.0
    - joblib==1.2.0
    - wandb==0.15.0
    - tensorboard==2.12.0